export const countryMap: Record<string, string> = {
  'united states': 'US',
  'usa': 'US',
  'america': 'US',
  'english': 'US',
  'united kingdom': 'GB',
  'uk': 'GB',
  'england': 'GB',
  'canada': 'CA',
  'german': 'DE',
  'germany': 'DE',
  'france': 'FR',
  'french': 'FR',
  'italy': 'IT',
  'spain': 'ES',
  'spanish': 'ES',
  'netherlands': 'NL',
  'belgium': 'BE',
  'switzerland': 'CH',
  'austria': 'AT',
  'portugal': 'PT',
  'ireland': 'IE',
  'sweden': 'SE',
  'norway': 'NO',
  'denmark': 'DK',
  'finland': 'FI',
  'poland': 'PL',
  'czech republic': 'CZ',
  'hungary': 'HU',
  'slovakia': 'SK',
  'slovenia': 'SI',
  'croatia': 'HR',
  'romania': 'RO',
  'bulgaria': 'BG',
  'greece': 'GR',
  'turkey': 'TR',
  'russia': 'RU',
  'ukraine': 'UA',
  'japan': 'JP',
  'south korea': 'KR',
  'china': 'CN',
  'india': 'IN',
  'australia': 'AU',
  'new zealand': 'NZ',
  'brazil': 'BR',
  'argentina': 'AR',
  'chile': 'CL',
  'mexico': 'MX',
  'south africa': 'ZA',
  'israel': 'IL',
  'saudi arabia': 'SA',
  'uae': 'AE',
  'singapore': 'SG',
  'thailand': 'TH',
  'malaysia': 'MY',
  'indonesia': 'ID',
  'philippines': 'PH',
  'vietnam': 'VN',
  'colombia': 'CO',
};

export const ALL_COUNTRIES: string[] = [
  "United States",
  "United Kingdom",
  "Canada",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Portugal",
  "Ireland",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Slovakia",
  "Slovenia",
  "Croatia",
  "Romania",
  "Bulgaria",
  "Greece",
  "Turkey",
  "Russia",
  "Ukraine",
  "Japan",
  "South Korea",
  "China",
  "India",
  "Australia",
  "New Zealand",
  "Brazil",
  "Argentina",
  "Chile",
  "Mexico",
  "South Africa",
  "Israel",
  "Saudi Arabia",
  "UAE",
  "Singapore",
  "Thailand",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Colombia",
];

export const getCountryCode = (countryName?: string): string | null => {
  if (!countryName) return null;
  return countryMap[countryName.toLowerCase()] || null;
};

export const getCountryFlag = (countryName?: string): string | null => {
  const code = getCountryCode(countryName);
  return code ? `/assets/flags/${code.toLowerCase()}.svg` : null;
};
